languageCode = "en"
languageName = "English"
title = ":: zhu424"

[params]
    subtitle = ":: zhu424 ::"
    owner = "Zhe You Liu"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

[params.logo]
    logoText = "zhu424"
    logoHomeLink = "/"

[menu]
# [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about"
#     weight = 1
# [[menu.main]]
#     identifier = "blog"
#     name = "Blog"
#     url = "https://blog.zhu424.dev/"
#     external = true
#     weight = 2
# [[menu.main]]
#     identifier = "contact"
#     name = "Contact"
#     url = "/contact"
#     weight = 3
# [[menu.main]]
#     identifier = "resume"
#     name = "Resume"
#     url = "https://github.com/jason810496/Resume/blob/main/LIU_ZHE_YOU.pdf"
#     external = true
#     weight = 4